# Generated by Django 2.2.3 on 2020-08-10 19:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=45, null=True)),
                ('drn', models.CharField(blank=True, max_length=45, null=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('uber_id', models.CharField(max_length=100)),
                ('uber_name', models.CharField(max_length=100)),
                ('approval_status', models.CharField(choices=[('Confirmed', 'Confirmed'), ('Pending', 'Pending')], max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Infraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('level', models.CharField(choices=[('Level one', 'one'), ('Level two', 'two'), ('Level three', 'three')], max_length=100, null=True)),
                ('points', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moove_id', models.CharField(max_length=100)),
                ('registration_no', models.CharField(max_length=100)),
                ('vin', models.CharField(max_length=100)),
                ('vehicle_plate', models.CharField(max_length=100)),
                ('assignment_status', models.CharField(choices=[('Assigned', 'Assigned'), ('Pending', 'Pending')], max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UberPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('cash_collected', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('trip_id', models.CharField(max_length=100)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uber_payments', to='driver.Driver')),
            ],
        ),
        migrations.CreateModel(
            name='Reconcilliation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('week_of', models.DateTimeField(blank=True, null=True)),
                ('earning', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('cash_collected', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('pos_receipt_url', models.CharField(max_length=100)),
                ('amount_owed', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('balance_brought', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconcilliations', to='driver.Driver')),
            ],
        ),
        migrations.CreateModel(
            name='InfractionRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('Infractions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infractionRecords', to='driver.Infraction')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infractions', to='driver.Driver')),
            ],
        ),
        migrations.CreateModel(
            name='DriverGPA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('current_gpa', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gpa', to='driver.Driver')),
            ],
        ),
        migrations.AddField(
            model_name='driver',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='driver.Plan'),
        ),
        migrations.AddField(
            model_name='driver',
            name='vehicle',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver', to='driver.Vehicle'),
        ),
    ]
