# Generated by Django 2.2.3 on 2020-08-14 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0002_auto_20200812_0944'),
    ]

    operations = [
        migrations.CreateModel(
            name='NigerianBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('institution_type', models.CharField(choices=[('Commercial Bank', 'Commercial Bank'), ('Others', 'Others')], max_length=100, null=True)),
                ('head_office_routing_code', models.CharField(max_length=100)),
                ('swift_bic_address', models.CharField(max_length=100)),
                ('bank_identifier', models.CharField(max_length=100)),
                ('street_address', models.CharField(max_length=255)),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='uberpayment',
            old_name='date',
            new_name='trip_time',
        ),
        migrations.AddField(
            model_name='uberpayment',
            name='date_exact',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uberpayment',
            name='item_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='DriverBankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=100)),
                ('bank_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banks', to='driver.NigerianBank')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='driver.Driver')),
            ],
        ),
    ]
