# Generated by Django 2.2.3 on 2020-08-18 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0006_auto_20200817_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverdailymetric',
            name='acceptance_rate',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=50),
        ),
        migrations.AlterField(
            model_name='driverdailymetric',
            name='adjusted_fare',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=50),
        ),
        migrations.AlterField(
            model_name='driverdailymetric',
            name='airport_surcharge',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=50),
        ),
        migrations.AlterField(
            model_name='driverdailymetric',
            name='cash_collected',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=50),
        ),
        migrations.AlterField(
            model_name='driverdailymetric',
            name='fare',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=50),
        ),
        migrations.AlterField(
            model_name='driverdailymetric',
            name='net_earnings',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=50),
        ),
        migrations.AlterField(
            model_name='driverdailymetric',
            name='rating',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=50),
        ),
        migrations.AlterField(
            model_name='driverdailymetric',
            name='surge',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=50),
        ),
        migrations.AlterField(
            model_name='driverdailymetric',
            name='total_card_amount',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=50),
        ),
        migrations.AlterField(
            model_name='driverdailymetric',
            name='total_cash_amount',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=50),
        ),
        migrations.AlterField(
            model_name='driverdailymetric',
            name='total_earned',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=50),
        ),
        migrations.AlterField(
            model_name='driverdailymetric',
            name='uber_fee',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=50),
        ),
        migrations.AlterField(
            model_name='drivergpa',
            name='current_gpa',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='infraction',
            name='points',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='reconcilliation',
            name='amount_owed',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='reconcilliation',
            name='balance_brought',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='reconcilliation',
            name='cash_collected',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='reconcilliation',
            name='earning',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='reconcilliation',
            name='pos_receipt_url',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='uberpayment',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='uberpayment',
            name='cash_collected',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True),
        ),
    ]
