# Generated by Django 2.2.3 on 2020-08-18 16:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0007_auto_20200818_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverdailymetric',
            name='acceptance_rate',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='driverdailymetric',
            name='adjusted_fare',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='driverdailymetric',
            name='airport_surcharge',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='driverdailymetric',
            name='cancellation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='driverdailymetric',
            name='card_payment_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='driverdailymetric',
            name='cash_collected',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='driverdailymetric',
            name='cash_payment_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='driverdailymetric',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='driverdailymetric',
            name='duration_online',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='driverdailymetric',
            name='fare',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='driverdailymetric',
            name='is_pos',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='driverdailymetric',
            name='net_earnings',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='driverdailymetric',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='driverdailymetric',
            name='surge',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='driverdailymetric',
            name='toll',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='driverdailymetric',
            name='total_card_amount',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='driverdailymetric',
            name='total_cash_amount',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='driverdailymetric',
            name='total_earned',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='driverdailymetric',
            name='trips',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='driverdailymetric',
            name='uber_fee',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='driverdailymetric',
            name='wait_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
