# Generated by Django 2.2.3 on 2020-08-25 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0009_auto_20200825_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverplanassignment',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='driver.Driver'),
        ),
    ]
