# Generated by Django 2.2.3 on 2020-08-28 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0011_auto_20200828_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverdailymetric',
            name='wait_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
