# Generated by Django 2.2.3 on 2020-08-28 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0012_driverdailymetric_wait_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverbankaccount',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
