# Generated by Django 2.2.3 on 2020-08-31 20:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0014_auto_20200831_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverdailymetric',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
