# Generated by Django 2.2.3 on 2020-09-01 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0015_auto_20200831_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverdailymetric',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
