# Generated by Django 2.2.3 on 2020-09-02 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0016_auto_20200901_1019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infractionrecord',
            old_name='Infractions',
            new_name='infractions',
        ),
        migrations.AlterField(
            model_name='drivergpa',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='infractionrecord',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reconcilliation',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
