# Generated by Django 2.2.3 on 2020-09-02 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0017_auto_20200902_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivergpa',
            name='total_deduction',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True),
        ),
    ]
