# Generated by Django 2.2.3 on 2020-09-02 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0018_drivergpa_total_deduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infraction',
            name='points',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=50),
        ),
    ]
