# Generated by Django 2.2.3 on 2020-09-07 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0021_opsmetric'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opsmetric',
            old_name='Vehicle_first_trip',
            new_name='vehicle_first_trip',
        ),
    ]
