# Generated by Django 2.2.3 on 2020-09-07 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0022_auto_20200907_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opsmetric',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
