# Generated by Django 2.2.3 on 2020-09-10 09:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0026_auto_20200909_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverplanassignment',
            name='effective_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='driverplanassignment',
            name='effective_start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='drivervehicleassignment',
            name='effective_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='drivervehicleassignment',
            name='effective_start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
