# Generated by Django 2.2.3 on 2020-09-10 10:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0027_auto_20200910_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivergpa',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='infractionrecord',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='possystem',
            name='effective_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='possystem',
            name='effective_start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='reconcilliation',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reconcilliation',
            name='week_of',
            field=models.DateField(blank=True, null=True),
        ),
    ]
