# Generated by Django 2.2.3 on 2020-09-10 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0028_auto_20200910_1002'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpsMetricSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_trips', models.IntegerField(blank=True, null=True)),
                ('supply_hours', models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True)),
                ('total_active_drivers', models.IntegerField(blank=True, null=True)),
                ('total_assigned_drivers', models.IntegerField(blank=True, null=True)),
                ('shd', models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True)),
                ('total_car_paid_incentives', models.IntegerField(blank=True, null=True)),
                ('average_tph_milestone', models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True)),
                ('average_fare', models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True)),
                ('average_earning_per_driver', models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True)),
                ('average_trips_per_driver', models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True)),
                ('cancellation_rate', models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True)),
                ('acceptance_rate', models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True)),
                ('p_non_cash', models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True)),
                ('p_pos_transaction', models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True)),
                ('p_non_cash_revenue', models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True)),
                ('p_pos_revenue', models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True)),
                ('uber_rating', models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True)),
                ('total_accidents', models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True)),
                ('total_apprehension', models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True)),
                ('total_recovery', models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True)),
                ('total_signup', models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True)),
                ('total_assessed', models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True)),
                ('total_approved', models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='opsmetric',
            name='cancellation_rate',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True),
        ),
        migrations.AddField(
            model_name='opsmetric',
            name='card_revenue',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True),
        ),
        migrations.AddField(
            model_name='opsmetric',
            name='cash_revenue',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True),
        ),
        migrations.AddField(
            model_name='opsmetric',
            name='p_non_cash_revenue',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True),
        ),
        migrations.AddField(
            model_name='opsmetric',
            name='p_pos_revenue',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True),
        ),
        migrations.AddField(
            model_name='opsmetric',
            name='pos_revenue',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True),
        ),
        migrations.AddField(
            model_name='opsmetric',
            name='trips_accepted',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opsmetric',
            name='virtual_account_revenue',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True),
        ),
    ]
