# Generated by Django 2.2.3 on 2020-09-10 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0029_auto_20200910_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='opsmetricsummary',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
