# Generated by Django 2.2.3 on 2020-09-16 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0031_virtualaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualaccount',
            name='virtual_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
