# Generated by Django 2.2.3 on 2020-10-09 16:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0033_auto_20201008_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='USSDVehicleAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ussd_ref', models.CharField(blank=True, max_length=50, null=True)),
                ('effective_start_date', models.DateField(default=django.utils.timezone.now)),
                ('effective_end_date', models.DateField(blank=True, null=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_ussd_ref', to='driver.Vehicle')),
            ],
        ),
    ]
