# Generated by Django 2.2.3 on 2020-10-12 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0034_ussdvehicleassignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ussdvehicleassignment',
            name='effective_end_date',
        ),
        migrations.RemoveField(
            model_name='ussdvehicleassignment',
            name='effective_start_date',
        ),
        migrations.AddField(
            model_name='ussdvehicleassignment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
