# Generated by Django 2.2.3 on 2020-10-13 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0035_auto_20201012_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='POSTerminal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('transaction', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('terminal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver.PosSystem')),
            ],
        ),
        migrations.CreateModel(
            name='POSReversal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True)),
                ('retrieval_ref_no', models.CharField(blank=True, max_length=255, null=True)),
                ('currency', models.CharField(blank=True, max_length=255, null=True)),
                ('stan', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('terminal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver.PosSystem')),
            ],
        ),
        migrations.CreateModel(
            name='POSNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('retrieval_ref_no', models.CharField(blank=True, max_length=255, null=True)),
                ('masked_pan', models.CharField(blank=True, max_length=255, null=True)),
                ('card_scheme', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('status_code', models.CharField(blank=True, max_length=255, null=True)),
                ('status_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('addnl_info', models.CharField(blank=True, max_length=255, null=True)),
                ('currency', models.CharField(blank=True, max_length=255, null=True)),
                ('merchant_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stan', models.CharField(blank=True, max_length=255, null=True)),
                ('card_expiry', models.CharField(blank=True, max_length=255, null=True)),
                ('card_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('terminal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver.PosSystem')),
            ],
        ),
    ]
