# Generated by Django 2.2.3 on 2020-10-15 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0037_auto_20201015_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualaccount',
            name='virtual_id',
            field=models.CharField(max_length=100),
        ),
    ]
