# Generated by Django 2.2.3 on 2020-10-15 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0038_auto_20201015_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverplanassignment',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='driver.Driver'),
        ),
        migrations.AlterField(
            model_name='driverplanassignment',
            name='plan',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='driver.Plan'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='drivervehicleassignment',
            name='driver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='driver_assingment', to='driver.Driver'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='drivervehicleassignment',
            name='vehicle',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_assingment', to='driver.Vehicle'),
            preserve_default=False,
        ),
    ]
