# Generated by Django 2.2.3 on 2020-10-19 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0039_auto_20201015_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='UberAllDriver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_deposit', models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True)),
                ('driver_id', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True)),
                ('trips', models.IntegerField(blank=True, null=True)),
                ('fare', models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True)),
                ('wait_time', models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True)),
                ('toll', models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True)),
                ('surge', models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True)),
                ('collection', models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True)),
                ('uber_fee', models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True)),
                ('payouts', models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True)),
                ('other_promotion', models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True)),
                ('tip', models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True)),
                ('airport_charge', models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True)),
                ('uber_fee_collection', models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True)),
                ('adjusted_fare', models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True)),
                ('uber_fee_collection_return', models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UberDriverPerformance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('net_fares', models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True)),
                ('per_trip', models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True)),
                ('per_hour_online', models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True)),
                ('per_km_on_trip', models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True)),
                ('trips', models.IntegerField(blank=True, null=True)),
                ('hours_online', models.TimeField(blank=True, null=True)),
                ('trips_per_hour', models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True)),
                ('distance_per_trip', models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True)),
                ('lifetime_rating', models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True)),
                ('acceptance', models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True)),
                ('driver_cancellation_rate', models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='uberpayment',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='uberpayment',
            name='disclaimer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uberpayment',
            name='driver_uuid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='uberpayment',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='uberpayment',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='uberpayment',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uberpayment',
            name='trip_uuid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uberpayment',
            name='item_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
