# Generated by Django 2.2.3 on 2020-10-21 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0041_auto_20201020_0833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uberpayment',
            name='cash_collected',
        ),
        migrations.RemoveField(
            model_name='uberpayment',
            name='trip_id',
        ),
        migrations.AddField(
            model_name='uberalldriver',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uberdriverperformance',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
