# Generated by Django 2.2.3 on 2020-10-23 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0042_auto_20201021_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(max_length=100)),
                ('identity', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='driver.Vehicle')),
            ],
        ),
    ]
