# Generated by Django 2.2.3 on 2020-11-02 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0044_drivermetric'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opsmetric',
            old_name='active_vehicles',
            new_name='average_trips_completed',
        ),
        migrations.RenameField(
            model_name='opsmetric',
            old_name='driver_first_trip',
            new_name='driver_assigned',
        ),
        migrations.RenameField(
            model_name='opsmetric',
            old_name='uber_qualified_incentives',
            new_name='driver_badge',
        ),
        migrations.RenameField(
            model_name='opsmetric',
            old_name='vehicle_first_trip',
            new_name='driver_invitation',
        ),
        migrations.RenameField(
            model_name='opsmetric',
            old_name='vehicle_signup',
            new_name='hackney_permit',
        ),
        migrations.RenameField(
            model_name='opsmetric',
            old_name='driver_approval_to_car_time',
            new_name='lasdri_attendance',
        ),
        migrations.AddField(
            model_name='opsmetric',
            name='inactive_vehicle',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opsmetric',
            name='insurance_coverage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opsmetric',
            name='lasdri_card',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opsmetric',
            name='lasdri_form',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opsmetric',
            name='lassra_attendance',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opsmetric',
            name='lassra_card',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opsmetric',
            name='licence_plate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opsmetric',
            name='number_plate_form',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opsmetric',
            name='police_cmr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opsmetric',
            name='proof_of_ownership',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opsmetric',
            name='road_worthiness_certificate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opsmetric',
            name='unassigned_vehicle',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opsmetric',
            name='vehicle_body_tag',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opsmetric',
            name='vehicle_intake',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opsmetric',
            name='vehicle_lga_doc',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opsmetric',
            name='vehicle_licence',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opsmetric',
            name='vehicle_recovries',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opsmetric',
            name='vehicle_repair',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opsmetric',
            name='vehicle_return',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
