# Generated by Django 2.2.3 on 2020-11-02 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0045_auto_20201102_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='opsmetric',
            name='driver_approval_to_car_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opsmetric',
            name='driver_first_trip',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
