# Generated by Django 2.2.3 on 2020-11-02 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0046_auto_20201102_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='opsmetric',
            name='active_vehicles',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opsmetric',
            name='uber_qualified_incentives',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
