# Generated by Django 2.2.3 on 2020-11-02 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0048_opsmetric_vehicle_first_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='opsmetricsummary',
            name='appointments',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True),
        ),
        migrations.AddField(
            model_name='opsmetricsummary',
            name='assigned',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True),
        ),
        migrations.AddField(
            model_name='opsmetricsummary',
            name='completion_rate',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True),
        ),
        migrations.AddField(
            model_name='opsmetricsummary',
            name='guarantor_form_submit',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True),
        ),
        migrations.AddField(
            model_name='opsmetricsummary',
            name='invitations',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True),
        ),
        migrations.AddField(
            model_name='opsmetricsummary',
            name='pre_approved',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True),
        ),
        migrations.AddField(
            model_name='opsmetricsummary',
            name='total_verified',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True),
        ),
    ]
