# Generated by Django 2.2.3 on 2020-11-03 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0049_auto_20201102_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='opsmetricsummary',
            name='total_return',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True),
        ),
    ]
