# Generated by Django 2.2.3 on 2020-11-03 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0051_auto_20201103_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='opsmetric',
            name='lasdri_attendance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opsmetric',
            name='lasdri_card',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opsmetric',
            name='lasdri_form',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opsmetric',
            name='lassra_attendance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opsmetric',
            name='lassra_card',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
