# Generated by Django 2.2.3 on 2020-11-19 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0052_auto_20201103_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uberpayment',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uber_payments', to='driver.Driver'),
        ),
    ]
