# Generated by Django 2.2.3 on 2020-11-24 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0053_auto_20201119_0914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uberalldriver',
            old_name='driver_id',
            new_name='uber_driver_id',
        ),
        migrations.AddField(
            model_name='uberalldriver',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uber_all_drivers', to='driver.Driver'),
        ),
    ]
