# Generated by Django 2.2.3 on 2020-12-03 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0055_auto_20201202_1340'),
    ]

    operations = [
        migrations.CreateModel(
            name='UberReconciliaition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_deposit', models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True)),
                ('uber_driver_id', models.CharField(blank=True, max_length=255, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True)),
                ('trips', models.IntegerField(blank=True, null=True)),
                ('fare', models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True)),
                ('wait_time', models.IntegerField(blank=True, null=True)),
                ('toll', models.IntegerField(blank=True, null=True)),
                ('surge', models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True)),
                ('collection', models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True)),
                ('uber_fee', models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True)),
                ('payouts', models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True)),
                ('other_promotion', models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True)),
                ('tip', models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True)),
                ('airport_charge', models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True)),
                ('uber_fee_collection', models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True)),
                ('adjusted_fare', models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True)),
                ('uber_fee_collection_return', models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True)),
                ('performance_date', models.DateField(blank=True, null=True)),
                ('driver_id', models.IntegerField(blank=True, null=True)),
                ('all_driver_name', models.CharField(blank=True, max_length=255, null=True)),
                ('performance_name', models.CharField(blank=True, max_length=255, null=True)),
                ('All_Drivers_date', models.DateField(blank=True, null=True)),
                ('net_fares', models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True)),
                ('per_trip', models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True)),
                ('per_hour_online', models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True)),
                ('per_km_on_trip', models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True)),
                ('trips_y', models.IntegerField(blank=True, null=True)),
                ('hours_online', models.TimeField(blank=True, null=True)),
                ('trips_per_hour', models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True)),
                ('distance_per_trip', models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True)),
                ('lifetime_rating', models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True)),
                ('acceptance', models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True)),
                ('driver_cancellation_rate', models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True)),
                ('master_uber_id', models.CharField(blank=True, max_length=255, null=True)),
                ('payments_date', models.DateField(blank=True, null=True)),
                ('cash_transactions', models.IntegerField(blank=True, null=True)),
                ('cash_amount', models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True)),
                ('pos_terminal_id', models.CharField(blank=True, max_length=255, null=True)),
                ('pos_transaction_date', models.DateField(blank=True, null=True)),
                ('pos_transaction_count', models.IntegerField(blank=True, null=True)),
                ('agg_pos_amount', models.DecimalField(blank=True, decimal_places=8, max_digits=50, null=True)),
                ('master_drn', models.CharField(blank=True, max_length=255, null=True)),
                ('driver_name', models.CharField(blank=True, max_length=255, null=True)),
                ('driver_email', models.CharField(blank=True, max_length=255, null=True)),
                ('driver_phone_number', models.CharField(blank=True, max_length=255, null=True)),
                ('reconciliation_date', models.DateField(blank=True, null=True)),
                ('reconciliaition_instance', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
