# Generated by Django 3.1.1 on 2020-12-11 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0061_vehiclestatusassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclestatusassignment',
            name='status',
            field=models.CharField(choices=[('Inactive', 'Inactive'), ('Active', 'Active'), ('Accident', 'Accident'), ('In Repair', 'In Repair')], default='Active', max_length=100),
        ),
    ]
