# Generated by Django 3.1.1 on 2020-12-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0062_auto_20201211_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='UberCredential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drn', models.CharField(blank=True, max_length=255, null=True)),
                ('driver_id', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('picture', models.URLField(blank=True, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=50, null=True)),
                ('activation_status', models.CharField(blank=True, max_length=255, null=True)),
                ('access_token', models.TextField(blank=True, null=True)),
                ('token_type', models.CharField(blank=True, max_length=255, null=True)),
                ('expires_in', models.IntegerField(blank=True, null=True)),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('scope', models.CharField(blank=True, max_length=255, null=True)),
                ('auth_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
