# Generated by Django 3.1.1 on 2020-12-14 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0063_ubercredential'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubercredential',
            name='picture',
            field=models.TextField(blank=True, null=True),
        ),
    ]
