version: '2.4'
services:

    unifiedDb:
        image: postgres:13-alpine
        volumes:
            - ./tmp-docker-vol/postgres:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=unifiedDb
            - POSTGRES_DATABASE=unifiedDb
            - POSTGRES_USER=unifiedDb

    unified-backend:  &unified-backend
        build: ./
        image: unified-backend
        cpu_shares: 2048
        volumes:
            - ../moove-unified-api:/usr/src/app/
        command: bash -c "pip install -r requirements.txt && bash ./docker/run.sh"
        environment: &unified-backend-env
            - ENV=local
            - DATABASE_URL=postgres://unifiedDb:unifiedDb@unifiedDb:5432/unifiedDb
        links:
            - unifiedDb
        ports:
            - 8000:8000
        expose:
            - "8000"
