# Generated by Django 3.1.6 on 2021-02-18 06:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroupings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('date_created', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('created_by', models.CharField(blank=True, max_length=105, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=105, null=True)),
                ('date_modified', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
            options={
                'db_table': 'user_groupings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=105, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_deleted', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('date_created', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('created_by', models.CharField(blank=True, max_length=105, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=105, null=True)),
                ('date_modified', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
            options={
                'db_table': 'user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=105, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('parent_permission_id', models.IntegerField(blank=True, null=True)),
                ('controller', models.CharField(blank=True, max_length=105, null=True)),
                ('method', models.CharField(blank=True, max_length=105, null=True)),
                ('is_deleted', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('date_created', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('created_by', models.CharField(blank=True, max_length=105, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=105, null=True)),
                ('date_modified', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
            options={
                'db_table': 'user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserRolePermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('date_created', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('created_by', models.CharField(blank=True, max_length=105, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=105, null=True)),
                ('date_modified', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
            options={
                'db_table': 'user_role_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserRoles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=105, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('parent_role_id', models.IntegerField(blank=True, null=True)),
                ('is_deleted', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('date_created', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('created_by', models.CharField(blank=True, max_length=105, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=105, null=True)),
                ('date_modified', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
            options={
                'db_table': 'user_roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=105, null=True)),
                ('last_name', models.CharField(blank=True, max_length=105, null=True)),
                ('email', models.CharField(blank=True, max_length=105, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=105, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=105, null=True)),
                ('date_created', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=105, null=True)),
                ('date_modified', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('is_deleted', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
